# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-06 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texasbrew', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='beer_description',
        ),
    ]
